repo: "randomize-starfield-banner"
canvasCourse: "467503"
canvasAssignment: "4394300"

naming: true
commits: 2
liveWebsite: true

html:
  - path: "index.html"
    locked: true

css:
  - path: "css/main.css"
    valid: true
    bestPractices: true
    search:
      - "transform-origin"
      - "animation"
      - "alternate"
      - "infinite"
      - "@keyframes"

js:
  - path: "js/main.js"
    valid: true
    bestPractices: true
    search:
      - "\\$\\('\\.banner'\\)"
      - '\.outerWidth\(\)'
      - '\.outerHeight\(\)'
      - '75'
      - 'for \('
      - 'i\+\+'
      - "\\$\\('<div>'\\)"
      - "\\.addClass\\('star'\\)"
      - '\.css\(\{'
      - 'top\:'
      - 'left\:'
      - 'opacity\:'
      - 'transform\:'
      - 'rotate\('
      - 'deg\)'
      - 'scale\('
      - 'Math\.random\(\)'
      - '\.append\('

functionality:
  - path: "index.html"
    tests:
      - |
        let banner = $('.banner');
        let stars = $$('.star');

        if (stars.length < 75) fail('There isn’t enough stars in the banner');
        if (css(stars[0]).top == css(stars[1]).top) fail('The stars’ `top` coordinate isn’t randomized');
        if (css(stars[2]).left == css(stars[3]).left) fail('The stars’ `left` coordinate isn’t randomized');
        if (css(stars[4]).opacity == css(stars[5]).opacity) fail('The stars’ `opacity` isn’t randomized');
        if (css(stars[6]).transform == css(stars[7]).transform) fail('The stars’ `transform` values aren’t randomized');
        if (!css(stars[8]).animationName || css(stars[8]).animationName == 'none') fail('The stars don’t have an `animation`');

        pass();
